#include "spi2_slave.h"


/* ============================================================================
 * External SPI2 handle
 * ============================================================================
 *
 * hspi2 is still initialized by CubeMX-generated main.c.
 *
 * We intentionally keep MX_SPI2_Init() in main.c so that CubeMX can continue
 * to regenerate the peripheral initialization safely.
 */

extern SPI_HandleTypeDef hspi2;


/* ============================================================================
 * Configuration
 * ============================================================================ */

/*
 * STM32H755 PE3 is connected to CM5 GPIO25.
 *
 * PE3 HIGH:
 *     One complete packet is ready.
 *
 * PE3 LOW:
 *     SPI transaction has completed or failed.
 */

#define SPI2_SLAVE_NOTIFY_PORT    CM5_TRIG_GPIO_Port
#define SPI2_SLAVE_NOTIFY_PIN     CM5_TRIG_Pin


/* ============================================================================
 * Debug counters
 * ============================================================================ */

volatile uint32_t SPI2_SlaveNotifyCount = 0U;
volatile uint32_t SPI2_SlaveTxCount = 0U;
volatile uint32_t SPI2_SlaveErrorCount = 0U;

volatile uint32_t SPI2_SlaveTxTimeoutCount = 0U;
volatile uint32_t SPI2_SlaveTxBusyCount = 0U;
volatile uint32_t SPI2_SlaveTxHalErrorCount = 0U;

volatile uint32_t SPI2_SlaveLastHalError = 0U;


/* ============================================================================
 * SPI2 Slave Send Packet
 * ============================================================================ */

HAL_StatusTypeDef SPI2_Slave_SendPacket(const uint8_t *data,
                                        uint16_t length)
{
    HAL_StatusTypeDef status;


    /*
     * Basic parameter validation.
     */
    if ((data == NULL) || (length == 0U))
    {
        SPI2_SlaveErrorCount++;

        return HAL_ERROR;
    }


    /*
     * --------------------------------------------------------
     * 1. Notify CM5
     * --------------------------------------------------------
     *
     * PE3 HIGH -> CM5 GPIO25 Rising Edge.
     *
     * This tells CM5:
     *
     *     "One complete packet is ready.
     *      Start SPI Master transaction."
     */
    HAL_GPIO_WritePin(SPI2_SLAVE_NOTIFY_PORT,
                      SPI2_SLAVE_NOTIFY_PIN,
                      GPIO_PIN_SET);


    /*
     * Count notification events generated by STM32.
     */
    SPI2_SlaveNotifyCount++;


    /*
     * --------------------------------------------------------
     * 2. Wait for CM5 SPI Master
     * --------------------------------------------------------
     *
     * STM32 is SPI Slave.
     *
     * STM32 does NOT generate SCK.
     *
     * CM5 must:
     *
     *     CS LOW
     *     generate SCK
     *     receive data
     *
     * Current bring-up implementation uses blocking HAL_SPI_Transmit().
     */
    status = HAL_SPI_Transmit(&hspi2,
                              (uint8_t *)data,
                              length,
                              1000U);


    /*
     * --------------------------------------------------------
     * 3. Release CM5 notification
     * --------------------------------------------------------
     *
     * PE3 LOW means:
     *
     *     SPI transaction finished
     *     or
     *     SPI transaction failed/timed out
     */
    HAL_GPIO_WritePin(SPI2_SLAVE_NOTIFY_PORT,
                      SPI2_SLAVE_NOTIFY_PIN,
                      GPIO_PIN_RESET);


    /*
     * --------------------------------------------------------
     * 4. Record result
     * --------------------------------------------------------
     */

    if (status == HAL_OK)
    {
        SPI2_SlaveTxCount++;
    }
    else
    {
        SPI2_SlaveErrorCount++;


        /*
         * Capture HAL SPI error code immediately.
         */
        SPI2_SlaveLastHalError =
            HAL_SPI_GetError(&hspi2);


        /*
         * Classify failure.
         */
        if (status == HAL_TIMEOUT)
        {
            SPI2_SlaveTxTimeoutCount++;

            /*
             * Yellow LED:
             *
             * HAL_SPI_Transmit() timeout.
             */
            BSP_LED_Toggle(LED_YELLOW);
        }
        else if (status == HAL_BUSY)
        {
            SPI2_SlaveTxBusyCount++;

            /*
             * Yellow LED:
             *
             * SPI peripheral busy.
             */
            BSP_LED_Toggle(LED_YELLOW);
        }
        else if (status == HAL_ERROR)
        {
            SPI2_SlaveTxHalErrorCount++;

            /*
             * Yellow LED:
             *
             * HAL SPI error.
             */
            BSP_LED_Toggle(LED_YELLOW);
        }
    }


    return status;
}